# Generated by Django 4.1 on 2022-08-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_commet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commet',
            new_name='Comment',
        ),
    ]
