# Generated by Django 4.1 on 2022-08-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_comment_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
