# Generated by Django 4.1 on 2022-08-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_alter_blog_post_options_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_post',
            options={'ordering': ('-created_on',)},
        ),
    ]
